version: "2.10.2"

services:
  node-app:
    build: 
      context: .

      #for multi-stage
      target: development
      
      #we can use condition on var on one stage
      #args:
      #  - NODE_ENV=development

    volumes: 
      - ./src:/app/src:ro
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    
    #overwrite cmd for one stage selon condition
    #command: npm run start-dev

# Run when file name is default (docker-compose.yml)
# docker-compose up -d  

# Run when file name isn't default
# docker-compose -f docker-compose.dev up -d  