version: "2.10.2"

services:
  node-app:
    container_name: node-app-container
    environment:
      - PORT=4000
    #env_file:
      #- ./.env
    ports:
      - "4000:4000"

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  mongo-db:

# Run when file name is default (docker-compose.yml)
# docker-compose up -d  

# Run when file name isn't default
# docker-compose -f docker-compose.dev up -d  